remote_theme: mmistakes/so-simple-theme
locale: "en-us"
title: Aaron Holbrook
baseurl: ""
url: "https://aaronholbrook.github.io"

logo: "/images/a7-dark-on-light.png"
copyright: "This site is made with :heart: by Aaron Holbrook."