locale: en-US
title: "Holbrook, Inc."
description: ":zap: Things I've learned. Stuff that matters. :100:"
baseurl: ""
url: https://aaronholbrook.github.io
logo: "/images/a7-dark-on-light.png"
date_format: "%B %-d, %Y"
read_time: true
permalink: /:title/
words_per_minute: 200
mathjax: true
google_fonts:
  - name: "Tajawal"
    weights: "400,400i,700,700i"
  - name: "Raleway"
    weights: "400,400i,500,500i"
  - name: "Source Code Pro"
    weights: "400,500"
google_analytics: "UA-24616230-1"
disqus:
  shortname: "aaronjholbrook"
twitter:
  username: aaronjholbrook

# Site
copyright: "Powered by :coffee: and :heart:"

# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
paginate: 10
paginate_path: /page:num/

# Search
search_full_content: false

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

whitelist:
  - jekyll-redirect-from

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true
  # Recipe defaults
  - scope:
      path: "_recipes"
      type: recipes
    values:
      layout: post
      comments: true
      share: true

# Site Author
author:
  name: Aaron Holbrook
  picture: /images/aaron-holbrook-photo.jpg
  email:
  twitter: aaronjholbrook
  links:
    - title: Twitter
      url: https://twitter.com/aaronjholbrook
      icon: fab fa-twitter-square
    - title: GitHub
      url: https://github.com/aaronholbrook
      icon: fab fa-github-square

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/aaronjholbrook
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/aaronholbrook
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
